export const MenuData = [
  /*Our Deals */

  {
    id: 1,
    name: "Deals",
    desc: "Special discount for you",
    bannerImg: "https://pngimg.com/uploads/box/box_PNG48.png",
    theme: { bgColor: "bg-[#f16a3d]", textColor: "text-black" },
    items: [
      {
        id: 1,
        name: "Royal Kabab Crust",
        price: "1,350",
        subCategory: "Special Deal",
        desc: "Signature stuffed crust pizza with premium kabab chunks and secret spices.",
        img: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=600",
        sizes: [
          { id: "rk-s1", name: "Standard (As is)", price: 200 },
          { id: "rk-s2", name: "Large Upgrade", price: 450 },
        ],
        addons: [
          { id: "rk-a1", name: "Extra Kabab Chunks", price: 250 },
          { id: "rk-a2", name: "Cheese Slice", price: 100 },
        ],
        extras: [{ id: "rk-e1", name: "White Sauce Dip", price: 60 }],
      },
      {
        id: 2,
        name: "Chicken Tikka",
        price: "1,220",
        subCategory: "Special Deal",
        desc: "Traditional tikka chunks & onions with a smoky charcoal flavor.",
        img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=600",
        sizes: [
          { id: "ct-s1", name: "Small", price: 200 },
          { id: "ct-s2", name: "Medium", price: 350 },
          { id: "ct-s3", name: "Large", price: 650 },
        ],
        addons: [
          { id: "ct-a1", name: "Extra Tikka Chunks", price: 180 },
          { id: "ct-a2", name: "Soft Drink (Can)", price: 150 },
        ],
        extras: [{ id: "ct-e1", name: "Extra Onions", price: 40 }],
      },
      {
        id: 3,
        name: "Chicken Fajita",
        price: "1,340",
        subCategory: "Special Deal",
        desc: "Mexican style marinated chicken with bell peppers and olives.",
        img: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=600",
        sizes: [
          { id: "cf-s1", name: "Regular", price: 200 },
          { id: "cf-s2", name: "Family Pack", price: 900 },
        ],
        addons: [
          { id: "cf-a1", name: "Extra Olives", price: 120 },
          { id: "cf-a2", name: "Mayo Garlic Dip", price: 70 },
        ],
        extras: [{ id: "cf-e1", name: "Stuffed Crust", price: 300 }],
      },
      {
        id: 4,
        name: "Chicken Lover",
        price: "1,410",
        subCategory: "Special Deal",
        desc: "Loaded with extra chicken, extra cheese, and our special ranch sauce.",
        img: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=600",
        sizes: [
          { id: "cl-s1", name: "Standard Lover", price: 100 },
          { id: "cl-s2", name: "Mega Feast", price: 550 },
        ],
        addons: [{ id: "cl-a1", name: "Double Cheese", price: 200 }],
        extras: [{ id: "cl-e1", name: "Fries Side", price: 220 }],
      },
    ],
  },

  /* Burger */
  {
    id: 2,
    name: "Burger",
    desc: "Juicy grilled burger",
    bannerImg: "https://www.pngarts.com/files/3/Chicken-Burger-PNG-Photo.png",
    theme: { bgColor: "bg-[#f16a3d]", textColor: "text-black" },

    items: [
      {
        id: 201,
        name: "Zingrato",
        price: "510",
        desc: "Our signature crispy zinger burger with fresh lettuce and premium mayo sauce.",
        img: "https://www.pngarts.com/files/3/Chicken-Burger-PNG-Photo.png",
        subCategory: "Zinger",
        sizes: [
          { id: "z1", name: "Standard", price: 200 },
          { id: "z2", name: "Double Patty Upgrade", price: 250 },
        ],
        addons: [
          { id: "za1", name: "Cheese Slice", price: 80 },
          { id: "za2", name: "Mayo Garlic Dip", price: 50 },
        ],
        extras: [{ id: "ze1", name: "Fries & Drink Combo", price: 350 }],
      },
      {
        id: 202,
        name: "Special Burger",
        price: "790",
        desc: "The ultimate Delight Crust special: Double patty, extra cheese, and our secret dressing.",
        img: "https://www.pngarts.com/files/3/Chicken-Burger-PNG-Photo.png",
        subCategory: "Special",
        sizes: [{ id: "s1", name: "Standard Special", price: 200 }],
        addons: [
          { id: "sa1", name: "Extra Patty", price: 300 },
          { id: "sa2", name: "Jalapenos", price: 60 },
        ],
        extras: [{ id: "se1", name: "Add Nuggets (4pcs)", price: 280 }],
      },
      {
        id: 203,
        name: "Grill Burger",
        price: "570",
        desc: "Perfectly flame-grilled juicy chicken patty with smoky BBQ flavor.",
        img: "https://www.pngarts.com/files/3/Chicken-Burger-PNG-Photo.png",
        subCategory: "Grilled",
        sizes: [
          { id: "g1", name: "Single Grill", price: 200 },
          { id: "g2", name: "Double Grill", price: 350 },
        ],
        addons: [
          { id: "ga1", name: "BBQ Sauce Drizzle", price: 40 },
          { id: "ga2", name: "Caramelized Onions", price: 70 },
        ],
        extras: [{ id: "ge1", name: "Extra Grilled Patty", price: 250 }],
      },
      {
        id: 204,
        name: "Reggy Burger",
        price: "390",
        desc: "Classic value burger with a tender patty and fresh veggies for a quick bite.",
        img: "https://www.pngarts.com/files/3/Chicken-Burger-PNG-Photo.png",
        subCategory: "Regular",
        sizes: [{ id: "r1", name: "Regular Size", price: 300 }],
        addons: [{ id: "ra1", name: "Cheese Slice", price: 80 }],
        extras: [{ id: "re1", name: "Soft Drink (Can)", price: 150 }],
      },
    ],
  },
  /* Pizza */

  {
    id: 3,
    name: "Pizza",
    desc: "Hot and cheesy pizza",
    bannerImg: "https://pngimg.com/uploads/pizza/pizza_PNG44095.png",
    theme: { bgColor: "bg-[#f18966]", textColor: "text-black" },

    items: [
      {
        id: 301,
        name: "Special Stuffer",
        price: "1,570",
        desc: "Bold and Flavorful! Our Special Sauce Tops and Coats the Base, With a Crust Stuffed With Marinated Seekh Kabab and Secret Sauce.",
        img: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=400",
        subCategory: "Royal Crust",
        sizes: [
          { id: "ps1", name: "Small (9 inch)", price: 200 },
          { id: "ps2", name: "Medium (12 inch)", price: 400 },
          { id: "ps3", name: "Large (14 inch)", price: 800 },
        ],
        addons: [
          { id: "pa1", name: "Extra Seekh Kabab", price: 250 },
          { id: "pa2", name: "Extra Cheese", price: 150 },
          { id: "pa3", name: "Mayo Garlic Dip", price: 60 },
          { id: "pa4", name: "Mineral Water", price: 100 },
        ],
        extras: [
          { id: "pe1", name: "Stuffed Crust", price: 300 },
          { id: "pe2", name: "Extra Topping", price: 200 },
        ],
      },
      {
        id: 302,
        name: "Special Delight",
        price: "1,350",
        desc: "Our house special signature pizza with premium toppings and extra cheese.",
        img: "https://tse3.mm.bing.net/th/id/OIP.DtdkVzEMzjPuS6fTPgDuhwHaEP?pid=Api&h=220&P=0",
        subCategory: "Royal Crust",
        sizes: [
          { id: "pd1", name: "Regular", price: 200 },
          { id: "pd2", name: "Large", price: 500 },
        ],
        addons: [
          { id: "pda1", name: "Extra Pepperoni", price: 180 },
          { id: "pda2", name: "Soft Drink (1.5L)", price: 250 },
        ],
        extras: [{ id: "pde1", name: "Cheese Burst", price: 350 }],
      },
      {
        id: 303,
        name: "Special Malai Boti ",
        price: "1,480",
        desc: "Creamy Malai Boti toppings, Melted Cheese, Fresh Tomato, and a Hint of Jalapenos.",
        img: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?q=80&w=400",
        subCategory: "Local Treats",
        sizes: [
          { id: "mb1", name: "Small", price: 200 },
          { id: "mb2", name: "Medium", price: 450 },
          { id: "mb3", name: "Large", price: 850 },
        ],
        addons: [
          { id: "mba1", name: "Extra Malai Boti", price: 220 },
          { id: "mba2", name: "Green Chillies", price: 30 },
        ],
        extras: [{ id: "mbe1", name: "Double Cheese", price: 250 }],
      },
      {
        id: 304,
        name: "Special Fajita ",
        price: "580",
        desc: "Bold and Satisfying! Our Special Sauce Base Topped With Juicy Tikka Chunks.",
        img: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=400",
        subCategory: "Local Treats",
        sizes: [
          { id: "sf1", name: "Personal", price: 300 },
          { id: "sf2", name: "Medium", price: 420 },
        ],
        addons: [
          { id: "sfa1", name: "Extra Veggies", price: 80 },
          { id: "sfa2", name: "Dip Sauce", price: 50 },
        ],
        extras: [{ id: "sfe1", name: "Fries Side", price: 200 }],
      },
      {
        id: 305,
        name: "Crown Crust",
        price: "1,650",
        desc: "A unique crust with mini-crowns filled with cheese or kabab.",
        img: "https://tse2.mm.bing.net/th/id/OIP.fWsOq-8f8bCO_wD_K4354AHaDt?pid=Api&h=220&P=0",
        subCategory: "Specialty",
        sizes: [
          { id: "cc1", name: "12 Inch Crown", price: 200 },
          { id: "cc2", name: "14 Inch Crown", price: 400 },
        ],
        addons: [
          { id: "cca1", name: "Crown Cheese Fill", price: 150 },
          { id: "cca2", name: "Crown Kabab Fill", price: 150 },
        ],
        extras: [{ id: "cce1", name: "Extra Meat Chunks", price: 250 }],
      },
      {
        id: 306,
        name: "Cheese Lover",
        price: "1,100",
        desc: "A heavenly blend of mozzarella, cheddar, and parmesan.",
        img: "https://static.vecteezy.com/system/resources/previews/053/458/864/non_2x/pepperoni-pizza-on-transparent-background-free-png.png",
        subCategory: "Specialty",
        sizes: [
          { id: "cl1", name: "Small", price: 200 },
          { id: "cl2", name: "Medium", price: 380 },
          { id: "cl3", name: "Large", price: 700 },
        ],
        addons: [
          { id: "cla1", name: "Extra Parmesan", price: 120 },
          { id: "cla2", name: "Cheese Dip", price: 70 },
        ],
        extras: [{ id: "cle1", name: "Sesame Crust", price: 40 }],
      },
      {
        id: 307,
        name: "Hot & Spicy",
        price: "630",
        desc: "Red chili flakes, jalapeños, and spicy chicken.",
        img: "https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?q=80&w=400",
        subCategory: "Classic Spicy",
        sizes: [{ id: "hs1", name: "Standard", price: 200 }],
        addons: [
          { id: "hsa1", name: "Extra Jalapeños", price: 80 },
          { id: "hsa2", name: "Chilli Flakes Pack", price: 20 },
        ],
        extras: [{ id: "hse1", name: "Drink (Can)", price: 150 }],
      },
      {
        id: 308,
        name: "Chicken Tikka",
        price: "580",
        desc: "Special Sauce on the Base, Tender Tikka Chicken and Melted Cheese.",
        img: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?q=80&w=400",
        subCategory: "Classic Spicy",
        sizes: [
          { id: "ct1", name: "Small", price: 200 },
          { id: "ct2", name: "Medium", price: 400 },
          { id: "ct3", name: "Large", price: 750 },
        ],
        addons: [
          { id: "cta1", name: "Extra Tikka", price: 180 },
          { id: "cta2", name: "Onions", price: 40 },
        ],
        extras: [{ id: "cte1", name: "Thick Crust", price: 100 }],
      },
    ],
  },
  /* Sandwich */

  {
    id: 4,
    name: "Sandwich",
    desc: "Toasted deli favorites",
    bannerImg: "https://www.pngarts.com/files/3/Sandwich-PNG-Photo.png",
    theme: { bgColor: "bg-[#f18966]", textColor: "text-black" },

    items: [
      {
        id: 401,
        name: "Club Sandwich",
        price: "650",
        desc: "Classic 3-layer sandwich with fresh egg, chicken, and crispy veggies.",
        img: "https://www.pngarts.com/files/3/Sandwich-PNG-Photo.png",
        subCategory: "Classic",
        sizes: [
          { id: "cs1", name: "Standard (4 Pieces)", price: 200 },
          { id: "cs2", name: "Large (6 Pieces)", price: 300 },
        ],
        addons: [
          { id: "ca1", name: "Extra Egg", price: 50 },
          { id: "ca2", name: "Cheese Slice", price: 80 },
          { id: "ca3", name: "Mayo Dip", price: 40 },
        ],
        extras: [
          { id: "ce1", name: "French Fries", price: 180 },
          { id: "ce2", name: "Coleslaw", price: 70 },
        ],
      },
      {
        id: 402,
        name: "Super Sandwich",
        price: "700",
        desc: "Extra loaded with premium chicken chunks and Delight Crust secret sauce.",
        img: "https://www.pngarts.com/files/3/Sandwich-PNG-Photo.png",
        subCategory: "Loaded",
        sizes: [{ id: "ss1", name: "Standard", price: 300 }],
        addons: [
          { id: "ssa1", name: "Extra Secret Sauce", price: 60 },
          { id: "ssa2", name: "Double Chicken", price: 250 },
          { id: "ssa3", name: "Soft Drink (Can)", price: 150 },
        ],
        extras: [{ id: "sse1", name: "Add Nuggets (4pcs)", price: 280 }],
      },
      {
        id: 403,
        name: "Grill Sandwich",
        price: "650",
        desc: "Perfectly toasted with spicy grilled chicken and melted cheese.",
        img: "https://www.pngarts.com/files/3/Sandwich-PNG-Photo.png",
        subCategory: "Grilled",
        sizes: [
          { id: "gs1", name: "Half Grill", price: 200 },
          { id: "gs2", name: "Full Grill", price: 450 },
        ],
        addons: [
          { id: "ga1", name: "Extra Grilled Chicken", price: 200 },
          { id: "ga2", name: "Jalapenos", price: 70 },
        ],
        extras: [{ id: "ge1", name: "Cheese Burst Toasting", price: 120 }],
      },
      {
        id: 404,
        name: "Mexican Sandwich",
        price: "800",
        desc: "Spicy Mexican style filling with jalapenos and tangy dressing.",
        img: "https://www.pngarts.com/files/3/Sandwich-PNG-Photo.png",
        subCategory: "Spicy",
        sizes: [{ id: "ms1", name: "Standard Size", price: 100 }],
        addons: [
          { id: "ma1", name: "Tangy Dressing Extra", price: 50 },
          { id: "ma2", name: "Olives", price: 80 },
          { id: "ma3", name: "Red Chilli Sauce", price: 30 },
        ],
        extras: [{ id: "me1", name: "Mexican Fries Side", price: 220 }],
      },
    ],
  },
  /* Roll Wrap */

  {
    id: 5,
    name: "Roll Wrap",
    desc: "Delicious tortilla wraps",
    bannerImg: "https://pngimg.com/uploads/kebab/kebab_PNG27.png",
    theme: { bgColor: "bg-[#f18966]", textColor: "text-black" },

    items: [
      {
        id: 501,
        name: "Chicken Roll",
        price: "250",
        desc: "Succulent roasted chicken chunks wrapped in paratha with garlic mayo.",
        img: "https://static.vecteezy.com/system/resources/previews/032/325/388/large_2x/spring-rolls-isolated-on-transparent-background-file-cut-out-ai-generated-png.png",
        subCategory: "Classic",
        sizes: [
          { id: "rs1", name: "Standard Roll", price: 200 },
          { id: "rs2", name: "Jumbo Roll", price: 150 },
        ],
        addons: [
          { id: "ra1", name: "Extra Mayo", price: 40 },
          { id: "ra2", name: "Cheese Slice", price: 80 },
          { id: "ra3", name: "Fresh Salad", price: 30 },
        ],
        extras: [
          { id: "re1", name: "Soft Drink (Can)", price: 150 },
          { id: "re2", name: "Extra Dip Sauce", price: 50 },
        ],
      },
      {
        id: 502,
        name: "Zinger Roll",
        price: "350",
        desc: "Crunchy golden zinger strips wrapped in a toasted paratha.",
        img: "https://cdn.pixabay.com/photo/2017/08/25/15/10/egg-roll-2680478_1280.jpg",
        subCategory: "Zinger",
        sizes: [
          { id: "zs1", name: "Single Zinger", price: 200 },
          { id: "zs2", name: "Double Zinger Fill", price: 180 },
        ],
        addons: [
          { id: "za1", name: "Extra Crispy Flakes", price: 30 },
          { id: "za2", name: "Spicy Mayo", price: 50 },
          { id: "za3", name: "Cheese Sauce", price: 90 },
        ],
        extras: [{ id: "ze1", name: "Fries (Small)", price: 120 }],
      },
      {
        id: 503,
        name: "B.B.Q Roll",
        price: "280",
        desc: "Smoky BBQ chicken chunks with onions and special tangy chutney.",
        img: "https://static.vecteezy.com/system/resources/previews/043/348/782/large_2x/chicken-shawarma-roll-isolated-on-transparent-background-png.png",
        subCategory: "Smoky",
        sizes: [{ id: "bs1", name: "Standard", price: 200 }],
        addons: [
          { id: "ba1", name: "Extra BBQ Sauce", price: 40 },
          { id: "ba2", name: "Extra Onions", price: 20 },
          { id: "ba3", name: "Imli Chutney", price: 40 },
        ],
        extras: [{ id: "be1", name: "Mineral Water (Half L)", price: 80 }],
      },
      {
        id: 504,
        name: "Mayo Garlic Roll",
        price: "300",
        desc: "Extra creamy roll loaded with premium garlic mayo and grilled chicken.",
        img: "https://png.pngtree.com/png-clipart/20250222/original/pngtree-high-quality-roti-roll-with-paneer-kathi-chicken-veg-and-egg-png-image_20493597.png",
        subCategory: "Creamy",
        sizes: [{ id: "ms1", name: "Standard Creamy", price: 300 }],
        addons: [
          { id: "ma1", name: "Double Mayo Garlic", price: 70 },
          { id: "ma2", name: "Melted Cheese", price: 100 },
        ],
        extras: [{ id: "me1", name: "Stuffed Paratha Upgrade", price: 60 }],
      },
      {
        id: 505,
        name: "Seekh Kabab Roll",
        price: "320",
        desc: "Two juicy seekh kababs wrapped with fresh salad and mint raita.",
        img: "https://static.vecteezy.com/system/resources/previews/043/764/379/non_2x/egg-roll-on-white-transparent-background-png.png",
        subCategory: "Classic",
        sizes: [
          { id: "ks1", name: "Standard (2 Kababs)", price: 200 },
          { id: "ks2", name: "Kabab Feast (3 Kababs)", price: 140 },
        ],
        addons: [
          { id: "ka1", name: "Extra Mint Raita", price: 30 },
          { id: "ka2", name: "Lachha Piaz", price: 30 },
          { id: "ka3", name: "Green Chilli Paste", price: 20 },
        ],
        extras: [{ id: "ke1", name: "Butter Toasted Paratha", price: 50 }],
      },
    ],
  },
  /* Local Treat */

  {
    id: 6,
    name: "Local Treats",
    desc: "Authentic local flavors",
    bannerImg:
      "https://pngimg.com/uploads/fried_chicken/fried_chicken_PNG14074.png",

    items: [
      {
        id: 601,
        name: "Chicken Roll",
        price: "250",
        desc: "Classic soft paratha filled with juicy roasted chicken chunks.",
        img: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
        subCategory: "Paratha Roll",
        sizes: [
          { id: "ls1", name: "Standard Paratha", price: 200 },
          { id: "ls2", name: "Jumbo Size", price: 120 },
        ],
        addons: [
          { id: "la1", name: "Extra Chicken Chunks", price: 150 },
          { id: "la2", name: "Mayo Garlic Sauce", price: 40 },
          { id: "la3", name: "Cheese Slice", price: 80 },
        ],
        extras: [
          { id: "le1", name: "Mint Raita", price: 30 },
          { id: "le2", name: "Soft Drink (Can)", price: 150 },
        ],
      },
      {
        id: 602,
        name: "Zinger Roll",
        price: "350",
        desc: "Crunchy fried zinger strips wrapped in a toasted paratha.",
        img: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?q=80&w=800",
        subCategory: "Paratha Roll",
        sizes: [
          { id: "lzs1", name: "Single Zinger Strip", price: 400 },
          { id: "lzs2", name: "Double Zinger Strip", price: 180 },
        ],
        addons: [
          { id: "lza1", name: "Extra Crunchy Mayo", price: 50 },
          { id: "lza2", name: "Jalapenos", price: 60 },
          { id: "lza3", name: "Cheese Sauce", price: 90 },
        ],
        extras: [{ id: "lze1", name: "Small Fries", price: 130 }],
      },
      {
        id: 603,
        name: "Kabab Roll",
        price: "300",
        desc: "Authentic grilled seekh kabab wrapped in paratha with tangy mint chutney.",
        img: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=800",
        subCategory: "Paratha Roll",
        sizes: [
          { id: "lks1", name: "Standard (2 Kababs)", price: 330 },
          { id: "lks2", name: "Full Feast (3 Kababs)", price: 150 },
        ],
        addons: [
          { id: "lka1", name: "Imli Chutney", price: 40 },
          { id: "lka2", name: "Lachha Piaz (Onions)", price: 20 },
        ],
        extras: [{ id: "lke1", name: "Extra Mint Raita", price: 30 }],
      },
      {
        id: 604,
        name: "Hot & Spicy Roll",
        price: "320",
        desc: "Chicken chunks tossed in extra spicy peri-peri sauce and jalapenos.",
        img: "https://thumbs.dreamstime.com/b/delicious-kunafa-recipe-middle-eastern-sweet-treat-transparent-background-392551920.jpg",
        subCategory: "Classic Spicy",
        sizes: [{ id: "hss1", name: "Standard Spicy", price: 100 }],
        addons: [
          { id: "hsa1", name: "Peri Peri Dip", price: 60 },
          { id: "hsa2", name: "Extra Jalapenos", price: 50 },
        ],
        extras: [{ id: "hse1", name: "Red Chilli Sauce", price: 30 }],
      },
      {
        id: 605,
        name: "Malai Boti Roll",
        price: "340",
        desc: "Creamy and mild malai boti chunks for a traditional smoky taste.",
        img: "https://static.vecteezy.com/system/resources/previews/048/045/181/non_2x/fresh-chicken-curry-isolated-on-transparent-background-free-png.png",
        subCategory: "Classic",
        sizes: [
          { id: "mbs1", name: "Standard Creamy", price: 280 },
          { id: "mbs2", name: "Jumbo Creamy", price: 160 },
        ],
        addons: [
          { id: "mba1", name: "Extra Cream/Malai", price: 70 },
          { id: "mba2", name: "Double Cheese", price: 140 },
        ],
        extras: [{ id: "mbe1", name: "Butter Toasted Paratha", price: 50 }],
      },
    ],
  },
  /* Pasta*/

  {
    id: 7,
    name: "Delicious Pasta",
    desc: "Creamy pasta bowls",
    bannerImg: "https://pngimg.com/uploads/pasta/pasta_PNG58.png",
    theme: { bgColor: "bg-[#f18966]", textColor: "text-black" },

    items: [
      {
        id: 701,
        name: "B.B.Q Pasta",
        price: "850",
        desc: "Smoky BBQ chicken chunks tossed in creamy white sauce.",
        img: "https://www.pngall.com/wp-content/uploads/2018/04/Pasta-PNG-Image.png",
        subCategory: "Creamy",
        sizes: [
          { id: "ps1", name: "Single Serving", price: 400 },
          { id: "ps2", name: "Family Bowl", price: 650 },
        ],
        addons: [
          { id: "pa1", name: "Extra BBQ Chicken", price: 250 },
          { id: "pa2", name: "Extra White Sauce", price: 100 },
          { id: "pa3", name: "Cheese Slice", price: 80 },
        ],
        extras: [
          { id: "pe1", name: "Garlic Bread (2pcs)", price: 150 },
          { id: "pe2", name: "Soft Drink (Can)", price: 180 },
        ],
      },
      {
        id: 702,
        name: "Chicken Pasta",
        price: "750",
        desc: "Classic Alfredo-style pasta with tender grilled chicken.",
        img: "https://pngimg.com/uploads/pasta/pasta_PNG58.png",
        subCategory: "Alfredo",
        sizes: [{ id: "ca1", name: "Standard Portion", price: 200 }],
        addons: [
          { id: "caa1", name: "Extra Grilled Chicken", price: 200 },
          { id: "caa2", name: "Mushrooms", price: 120 },
        ],
        extras: [{ id: "cae1", name: "Extra Parmesan Cheese", price: 150 }],
      },
      {
        id: 703,
        name: "Fettuccine Alfredo",
        price: "950",
        desc: "Rich butter and parmesan cheese sauce with flat fettuccine noodles.",
        img: "https://static.vecteezy.com/system/resources/previews/050/566/210/non_2x/heap-of-tasty-raw-penne-pasta-transparent-background-png.png",
        subCategory: "Alfredo",
        sizes: [
          { id: "fa1", name: "Regular", price: 300 },
          { id: "fa2", name: "Large", price: 400 },
        ],
        addons: [
          { id: "faa1", name: "Extra Alfredo Sauce", price: 150 },
          { id: "faa2", name: "Broccoli", price: 90 },
        ],
        extras: [{ id: "fae1", name: "Garlic Bread with Cheese", price: 220 }],
      },
      {
        id: 704,
        name: "Spicy Arrabbiata",
        price: "700",
        desc: "Penne pasta in a fiery tomato sauce with garlic and dried red chili peppers.",
        img: "https://static.vecteezy.com/system/resources/previews/046/934/343/non_2x/pasta-in-a-bowl-on-transparent-background-png.png",
        subCategory: "Spicy",
        sizes: [{ id: "sa1", name: "Standard Bowl", price: 100 }],
        addons: [
          { id: "saa1", name: "Extra Spicy Sauce", price: 50 },
          { id: "saa2", name: "Black Olives", price: 80 },
          { id: "saa3", name: "Red Chilli Flakes", price: 20 },
        ],
        extras: [{ id: "sae1", name: "Add Grilled Chicken", price: 200 }],
      },
      {
        id: 705,
        name: "Mac & Cheese",
        price: "650",
        desc: "Classic elbow macaroni baked in a golden three-cheese blend.",
        img: "https://tse3.mm.bing.net/th/id/OIP.iGjfagrUXqsSR8TJPuQCnQAAAA?pid=Api&h=220&P=0",
        subCategory: "Creamy",
        sizes: [
          { id: "mc1", name: "Standard Serving", price: 200 },
          { id: "mc2", name: "Kids Portion", price: 150 },
        ],
        addons: [
          { id: "mca1", name: "Double Cheese Blend", price: 180 },
          { id: "mca2", name: "Crispy Breadcrumbs", price: 40 },
        ],
        extras: [{ id: "mce1", name: "Potato Fries Side", price: 150 }],
      },
      {
        id: 706,
        name: "Chicken Lasagna",
        price: "1,150",
        desc: "Layers of pasta, seasoned chicken, and mozzarella baked to perfection.",
        img: "https://pngimg.com/uploads/pasta/pasta_PNG91.png",
        subCategory: "Baked",
        sizes: [
          { id: "cl1", name: "Single Slab", price: 200 },
          { id: "cl2", name: "Full Tray", price: 2200 },
        ],
        addons: [
          { id: "cla1", name: "Extra Layer of Cheese", price: 200 },
          { id: "cla2", name: "Extra Meat Sauce", price: 180 },
        ],
        extras: [{ id: "cle1", name: "Special Dip Sauce", price: 60 }],
      },
    ],
  },
  //Fried Potatoes
  {
    id: 8,
    name: "Fried Potatoes",
    desc: "Crispy and golden potato delights",
    bannerImg: "https://pngimg.com/uploads/fries/fries_PNG48.png",
    theme: { bgColor: "bg-[#ffc107]", textColor: "text-black" },

    items: [
      {
        id: 801,
        name: "Classic Salted Fries",
        price: "220",
        desc: "Traditional crispy golden fries with a pinch of sea salt.",
        img: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?q=80&w=400",
        subCategory: "Classic",
        sizes: [
          { id: "fs1", name: "Regular", price: 100 },
          { id: "fs2", name: "Large", price: 130 },
          { id: "fs3", name: "Jumbo Bucket", price: 280 },
        ],
        addons: [
          { id: "fa1", name: "Extra Salt Packet", price: 0 },
          { id: "fa2", name: "Ketchup Sachet", price: 10 },
          { id: "fa3", name: "Mayo Dip", price: 50 },
        ],
        extras: [{ id: "fe1", name: "Masala Sprinkle", price: 20 }],
      },
      {
        id: 802,
        name: "Masala Fries",
        price: "280",
        desc: "Fries tossed in our signature spicy desi masala mix.",
        img: "https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?q=80&w=400",
        subCategory: "Spicy",
        sizes: [
          { id: "ms1", name: "Standard", price: 200 },
          { id: "ms2", name: "Large", price: 120 },
        ],
        addons: [
          { id: "ma1", name: "Extra Masala", price: 30 },
          { id: "ma2", name: "Green Chutney Dip", price: 40 },
        ],
        extras: [{ id: "me1", name: "Soft Drink (Can)", price: 150 }],
      },
      {
        id: 803,
        name: "Mayo Garlic Fries",
        price: "350",
        desc: "Crispy fries loaded with creamy garlic mayo and parsley.",
        img: "https://images.pexels.com/photos/115740/pexels-photo-115740.jpeg?auto=compress&cs=tinysrgb&w=400",
        subCategory: "Loaded",
        sizes: [
          { id: "mgs1", name: "Standard Bowl", price: 200 },
          { id: "mgs2", name: "Mega Loaded", price: 200 },
        ],
        addons: [
          { id: "mga1", name: "Double Mayo Garlic", price: 80 },
          { id: "mga2", name: "Cheese Sauce Drizzle", price: 100 },
        ],
        extras: [{ id: "mge1", name: "Add Jalapenos", price: 60 }],
      },
      {
        id: 804,
        name: "Pizza Fries",
        price: "550",
        desc: "Fries topped with pizza sauce, melted cheese, olives, and chicken chunks.",
        img: "https://images.unsplash.com/photo-1585109649139-366815a0d713?q=80&w=400",
        subCategory: "Specialty",
        sizes: [
          { id: "pfs1", name: "Standard Serving", price: 300 },
          { id: "pfs2", name: "Family Platter", price: 500 },
        ],
        addons: [
          { id: "pfa1", name: "Extra Pizza Cheese", price: 150 },
          { id: "pfa2", name: "Extra Chicken Chunks", price: 200 },
          { id: "pfa3", name: "Black Olives", price: 50 },
          { id: "pfa4", name: "Mushrooms", price: 80 },
        ],
        extras: [
          { id: "pfe1", name: "Stuffed Crust Base", price: 100 },
          { id: "pfe2", name: "Garlic Bread Side", price: 150 },
        ],
      },
    ],
  },
  // Beverages
  {
    id: 9,
    name: "Beverages",
    desc: "Refreshing drinks to quench your thirst",
    bannerImg:
      "https://static.vecteezy.com/system/resources/thumbnails/056/614/973/small_2x/flavored-soda-isolate-on-transparent-background-png.png",
    theme: { bgColor: "bg-[#007bff]", textColor: "text-white" },
    items: [
      {
        id: 901,
        name: "Soft Drink (Can)",
        price: "180",
        desc: "Pepsi, Coke, 7up, or Dew (330ml).",
        img: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?q=80&w=400",
        subCategory: "Cold Drinks",
        sizes: [
          { id: "bv-s1", name: "330ml Can", price: 50 },
          { id: "bv-s2", name: "500ml Pet", price: 70 },
          { id: "bv-s3", name: "1.5L Bottle", price: 150 },
        ],
        addons: [
          { id: "bv-a1", name: "Extra Ice", price: 200 },
          { id: "bv-a2", name: "Fresh Lime Squeeze", price: 40 },
        ],
        extras: [{ id: "bv-e1", name: "Disposable Glass", price: 30 }],
      },
      {
        id: 902,
        name: "Fresh Lime (Chilled)",
        price: "220",
        desc: "Refreshing lemon soda with a hint of black salt and mint.",
        img: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?q=80&w=400",
        subCategory: "Mocktails",
        sizes: [
          { id: "fl-s1", name: "Standard Glass", price: 100 },
          { id: "fl-s2", name: "Jumbo Glass", price: 100 },
        ],
        addons: [
          { id: "fl-a1", name: "Extra Mint", price: 20 },
          { id: "fl-a2", name: "Extra Masala", price: 20 },
        ],
        extras: [{ id: "fl-e1", name: "Reusable Straw", price: 20 }],
      },
      {
        id: 903,
        name: "Blue Lagoon",
        price: "380",
        desc: "Classic blue curacao syrup mixed with lemon juice and sprite.",
        img: "https://images.unsplash.com/photo-1536935338788-846bb9981813?q=80&w=400",
        subCategory: "Mocktails",
        sizes: [{ id: "bl-s1", name: "Standard Glass", price: 200 }],
        addons: [
          { id: "bl-a1", name: "Ice Cream Scoop", price: 150 },
          { id: "bl-a2", name: "Extra Syrup", price: 50 },
        ],
        extras: [],
      },
      {
        id: 904,
        name: "Oreo Shake",
        price: "490",
        desc: "Thick milk shake blended with original Oreo cookies.",
        img: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?q=80&w=400",
        subCategory: "Shakes",
        sizes: [
          { id: "os-s1", name: "Regular", price: 300 },
          { id: "os-s2", name: "Large", price: 200 },
        ],
        addons: [
          { id: "os-a1", name: "Extra Oreo Crumb", price: 60 },
          { id: "os-a2", name: "Chocolate Syrup", price: 50 },
          { id: "os-a3", name: "Ice Cream Scoop", price: 150 },
        ],
        extras: [{ id: "os-e1", name: "Whipped Cream Top", price: 100 }],
      },
      {
        id: 905,
        name: "Cappuccino",
        price: "350",
        desc: "Classic Italian coffee with a rich layer of foam.",
        img: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?q=80&w=400",
        subCategory: "Hot Drinks",
        sizes: [
          { id: "cp-s1", name: "Standard Mug", price: 100 },
          { id: "cp-s2", name: "Tall Mug", price: 150 },
        ],
        addons: [
          { id: "cp-a1", name: "Extra Shot Espresso", price: 120 },
          { id: "cp-a2", name: "Extra Sugar/Syrup", price: 30 },
          { id: "cp-a3", name: "Caramel Drizzle", price: 50 },
        ],
        extras: [{ id: "cp-e1", name: "Cookie on Side", price: 40 }],
      },
      {
        id: 916,
        name: "Mineral Water",
        price: "90",
        desc: "Chilled and purified drinking water (500ml).",
        img: "https://www.seriouseats.com/thmb/EZl4Zc_wCuxUt25XxbBFxqIzqhc=/1500x1125/filters:fill(auto,1)/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__images__2017__06__20170620-water-bottle-vicky-wasik-group1-210a332e1342467b8eea4f804ca935b4.jpg",
        subCategory: "Water",
        sizes: [
          { id: "mw-s1", name: "500ml Bottle", price: 200 },
          { id: "mw-s2", name: "1.5L Bottle", price: 70 },
        ],
        addons: [],
        extras: [{ id: "mw-e1", name: "Disposable Cups (2)", price: 20 }],
      },
    ],
  },
  // Crispy & Chicken
  {
    id: 10,
    name: "Crispy & Chicken",
    desc: "Golden fried and crunchy chicken treats",
    bannerImg:
      "https://static.vecteezy.com/system/resources/previews/025/229/888/original/crispy-fried-chicken-isolated-on-transparent-background-free-png.png",
    theme: { bgColor: "bg-[#e21b1b]", textColor: "text-white" },

    items: [
      {
        id: 1001,
        name: "Fried Chicken (2 Pcs)",
        price: "450",
        desc: "Juicy on the inside, extra crispy on the outside. Served with dip.",
        img: "https://static.vecteezy.com/system/resources/previews/024/724/510/non_2x/hot-and-crispy-fried-chicken-isolated-on-transparent-background-fresh-pieces-of-crispy-fried-chicken-fast-food-generative-ai-png.png",
        subCategory: "Fried Chicken",
        sizes: [
          { id: "fc-s1", name: "2 Pieces", price: 200 },
          { id: "fc-s2", name: "5 Pieces", price: 600 },
          { id: "fc-s3", name: "9 Pieces (Family)", price: 1400 },
        ],
        addons: [
          { id: "fc-a1", name: "Extra Dip Sauce", price: 50 },
          { id: "fc-a2", name: "Dinner Roll", price: 40 },
        ],
        extras: [
          { id: "fc-e1", name: "Coleslaw", price: 80 },
          { id: "fc-e2", name: "Fries Side", price: 150 },
        ],
      },
      {
        id: 1002,
        name: "Hot Wings (10 Pcs)",
        price: "650",
        desc: "Spicy and tangy wings tossed in our signature buffalo sauce.",
        img: "https://static.vecteezy.com/system/resources/previews/024/724/529/non_2x/hot-and-crispy-fried-chicken-isolated-on-transparent-background-fresh-pieces-of-crispy-fried-chicken-fast-food-generative-ai-free-png.png",
        subCategory: "Wings",
        sizes: [
          { id: "hw-s1", name: "10 Pieces", price: 200 },
          { id: "hw-s2", name: "20 Pieces", price: 550 },
        ],
        addons: [
          { id: "hw-a1", name: "Extra Buffalo Sauce", price: 60 },
          { id: "hw-a2", name: "Ranch Dip", price: 70 },
        ],
        extras: [{ id: "hw-e1", name: "Soft Drink (Can)", price: 180 }],
      },
      {
        id: 1003,
        name: "Chicken Nuggets (6 Pcs)",
        price: "380",
        desc: "Bite-sized golden nuggets made from 100% chicken breast.",
        img: "https://static.vecteezy.com/system/resources/previews/036/627/221/large_2x/ai-generated-golden-crispy-chicken-tenders-on-transparent-background-png.png",
        subCategory: "Snacks",
        sizes: [
          { id: "ng-s1", name: "6 Pieces", price: 200 },
          { id: "ng-s2", name: "12 Pieces", price: 320 },
        ],
        addons: [
          { id: "ng-a1", name: "Honey Mustard Dip", price: 60 },
          { id: "ng-a2", name: "Garlic Mayo Dip", price: 50 },
        ],
        extras: [{ id: "ng-e1", name: "Toy (Kids Meal)", price: 100 }],
      },
      {
        id: 1004,
        name: "Chicken Tenders",
        price: "520",
        desc: "Hand-breaded premium chicken strips served with honey mustard.",
        img: "https://thumbs.dreamstime.com/b/plate-crispy-fried-chicken-isolated-transparent-background-360438966.jpg",
        subCategory: "Fried Chicken",
        sizes: [
          { id: "ct-s1", name: "3 Pieces", price: 300 },
          { id: "ct-s2", name: "5 Pieces", price: 350 },
        ],
        addons: [
          { id: "ct-a1", name: "Extra Honey Mustard", price: 60 },
          { id: "ct-a2", name: "BBQ Dip", price: 60 },
        ],
        extras: [{ id: "ct-e1", name: "Peri Peri Seasoning", price: 30 }],
      },
      {
        id: 1005,
        name: "Popcorn Chicken",
        price: "400",
        desc: "Small, crunchy chicken bites perfect for snacking on the go.",
        img: "https://thumbs.dreamstime.com/b/delicious-crispy-fried-chicken-paper-isolated-transparent-background-delicious-crispy-fried-chicken-paper-isolated-362187819.jpg",
        subCategory: "Snacks",
        sizes: [
          { id: "pc-s1", name: "Standard Tub", price: 200 },
          { id: "pc-s2", name: "Jumbo Tub", price: 300 },
        ],
        addons: [
          { id: "pc-a1", name: "Cheese Topping", price: 100 },
          { id: "pc-a2", name: "Spicy Mayo Drizzle", price: 50 },
        ],
        extras: [{ id: "pc-e1", name: "Finger Chips Side", price: 150 }],
      },
    ],
  },
];
